### ISSUE TITLE
Module style not compatible with TypeScript

### ISSUE THREAD

**Issue by michaelbromley** [antonmedv/codejar#13]
Hi, first of all let me say that I absolutely love the simplicity and elegance of this lib 👍 

I am using it in a TypeScript project and was surprised to see that, although this is written in TS, it is not readily consumable from a TS project.

The reason is the "revealing module" pattern used for the main `CodeJar` function. When constructing the function with the `new` keyword, TypeScript cannot infer the type of the returned object. Additionally, even though CodeJar can be constructed like a class, it is only a value and there is no corresponding `CodeJar` type, which is rather unexpected for a TypeScript user.

```ts
import { CodeJar } from 'codejar';

// ..
let jar: CodeJar;
// TS2749: 'CodeJar' refers to a value, but is being used as a type here.

jar = new CodeJar(element, highlight);
// TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type
```

It is possible to get things working with a little bit of TS trickery:

```ts
import { CodeJar } from 'codejar';

//..
let jar: ReturnType<typeof CodeJar>;

jar = CodeJar(element, highlight);
// works without "new", and "jar" instance has correct type with auto-complete etc.
```

## Solution

I can see 2 possible solutions:

1. Add some docs with a TypeScript example (less work, but weirder for TS end-users)
2. Refactor the `CodeJar` module function to a regular ES6 class (more work, but results in expected behaviour in TS)

What do you think? I'd be willing to put in a PR for either of the above solutions if you agree.

**Comment by antonmedv** [comment]
Actually I went from a class to a function. As minification of such is much much better. But decided to leave new keyword in docs. Maybe it’s more easy to just use it as function?

Another solution will be to add .d.ts and omit ts fine in package. But more work on keeping them synked.

**Comment by michaelbromley** [comment]
> Actually I went from a class to a function. As minification of such is much much better.
Ah that makes a lot more sense now.  I personally find it less confusing if the `new` keyword would be omitted from the docs - then TS type inference would "just work" on the return type of `CodeJar()`.

Might I then suggest, in addition to updating the docs to remove "new", that the following be added to the TS:

```ts
export type CodeJar = ReturnType<typeof CodeJar>;
```

This would then allow `CodeJar` to be used in both value-space and type-space and yield the expected result, i.e.

```ts
import { CodeJar } from 'codejar';

const codeJar: CodeJar = CodeJar(/* ... */);
```

**Comment by bluebrown** [comment]
I always get just this `Cannot find module 'codejar'.ts(2307)`. So the trick does not work if the import already errors. Do I have to bust out webpack or something?

**Comment by antonmedv** [comment]
It should be fixed now. Please check v.3.0.0.

**Comment by bluebrown** [comment]
Thanks for working on this. I still get this with the new version.

![image](https://user-images.githubusercontent.com/39703898/82362986-1c633880-9a05-11ea-8162-a9096db03512.png)

![image](https://user-images.githubusercontent.com/39703898/82363053-343abc80-9a05-11ea-8f50-936658cfad0b.png)

**Comment by michaelbromley** [comment]
@bluebrown The change is v3.0.0 is simply to remove the use of the "new" keyword in the docs. Do the same in your code and it should work as expected.
